export const FETCH_PRODUCTS='FETCH_PRODUCTS';
export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const ORDER_PRODUCTS_BY_SIZE='ORDER_PRODUCTS_BY_SIZE';
export const SORT_PRODUCTS_BY_PRICE='SORT_PRODUCTS_BY_PRICE';